# --- Sample dataset

# --- !Ups

insert into company (id,name) values (  1,'Apple Inc.');
insert into company (id,name) values (  2,'Thinking Machines');
insert into company (id,name) values (  3,'RCA');
insert into company (id,name) values (  4,'Netronics');
insert into company (id,name) values (  5,'Tandy Corporation');
insert into company (id,name) values (  6,'Commodore International');
insert into company (id,name) values (  7,'MOS Technology');
insert into company (id,name) values (  8,'Micro Instrumentation and Telemetry Systems');
insert into company (id,name) values (  9,'IMS Associates, Inc.');
insert into company (id,name) values ( 10,'Digital Equipment Corporation');
insert into company (id,name) values ( 11,'Lincoln Laboratory');
insert into company (id,name) values ( 12,'Moore School of Electrical Engineering');
insert into company (id,name) values ( 13,'IBM');
insert into company (id,name) values ( 14,'Amiga Corporation');
insert into company (id,name) values ( 15,'Canon');
insert into company (id,name) values ( 16,'Nokia');
insert into company (id,name) values ( 17,'Sony');
insert into company (id,name) values ( 18,'OQO');
insert into company (id,name) values ( 19,'NeXT');    
insert into company (id,name) values ( 20,'Atari');
insert into company (id,name) values ( 22,'Acorn computer');
insert into company (id,name) values ( 23,'Timex Sinclair');
insert into company (id,name) values ( 24,'Nintendo');
insert into company (id,name) values ( 25,'Sinclair Research Ltd');
insert into company (id,name) values ( 26,'Xerox');
insert into company (id,name) values ( 27,'Hewlett-Packard');
insert into company (id,name) values ( 28,'Zemmix');
insert into company (id,name) values ( 29,'ACVS');
insert into company (id,name) values ( 30,'Sanyo');
insert into company (id,name) values ( 31,'Cray');
insert into company (id,name) values ( 32,'Evans & Sutherland');    
insert into company (id,name) values ( 33,'E.S.R. Inc.');
insert into company (id,name) values ( 34,'OMRON');
insert into company (id,name) values ( 35,'BBN Technologies');
insert into company (id,name) values ( 36,'Lenovo Group');
insert into company (id,name) values ( 37,'ASUS');
insert into company (id,name) values ( 38,'Amstrad');
insert into company (id,name) values ( 39,'Sun Microsystems');
insert into company (id,name) values ( 40,'Texas Instruments');
insert into company (id,name) values ( 41,'HTC Corporation');
insert into company (id,name) values ( 42,'Research In Motion');
insert into company (id,name) values ( 43,'Samsung Electronics');

insert into computer (id,name,introduced,discontinued,company_id) values (  1,'MacBook Pro 15.4 inch',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (  2,'CM-2a',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (  3,'CM-200',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (  4,'CM-5e',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (  5,'CM-5','1991-01-01',null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (  6,'MacBook Pro','2006-01-10',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (  7,'Apple IIe',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (  8,'Apple IIc',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (  9,'Apple IIGS',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 10,'Apple IIc Plus',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 11,'Apple II Plus',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 12,'Apple III','1980-05-01','1984-04-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 13,'Apple Lisa',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 14,'CM-2',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values ( 15,'Connection Machine','1987-01-01',null,2);
insert into computer (id,name,introduced,discontinued,company_id) values ( 16,'Apple II','1977-04-01','1993-10-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 17,'Apple III Plus','1983-12-01','1984-04-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 18,'COSMAC ELF',null,null,3);
insert into computer (id,name,introduced,discontinued,company_id) values ( 19,'COSMAC VIP','1977-01-01',null,3);
insert into computer (id,name,introduced,discontinued,company_id) values ( 20,'ELF II','1977-01-01',null,4);
insert into computer (id,name,introduced,discontinued,company_id) values ( 21,'Macintosh','1984-01-24',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 22,'Macintosh II',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 23,'Macintosh Plus','1986-01-16','1990-10-15',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 24,'Macintosh IIfx',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 25,'iMac','1998-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 26,'Mac Mini','2005-01-22',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 27,'Mac Pro','2006-08-07',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 28,'Power Macintosh','1994-03-01','2006-08-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 29,'PowerBook','1991-01-01','2006-01-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 30,'Xserve',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 31,'Powerbook 100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 32,'Powerbook 140',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 33,'Powerbook 170',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 34,'PowerBook Duo',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 35,'PowerBook 190',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 36,'Macintosh Quadra','1991-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 37,'Macintosh Quadra 900',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 38,'Macintosh Quadra 700',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 39,'Macintosh LC','1990-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 40,'Macintosh LC II','1990-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 41,'Macintosh LC III','1993-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 42,'Macintosh LC III+',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 43,'Macintosh Quadra 605','1993-10-21',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 44,'Macintosh LC 500 series',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 45,'TRS-80 Color Computer','1980-01-01',null,5);
insert into computer (id,name,introduced,discontinued,company_id) values ( 46,'Acorn System 2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 47,'Dragon 32/64',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 48,'MEK6800D2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 49,'Newbear 77/68',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 50,'Commodore PET',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( 51,'Commodore 64','1982-08-01','1994-01-01',6);
insert into computer (id,name,introduced,discontinued,company_id) values ( 52,'Commodore 64C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 53,'Commodore SX-64',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( 54,'Commodore 128',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( 55,'Apple I','1976-04-01','1977-10-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 56,'KIM-1','1975-01-01',null,7);
insert into computer (id,name,introduced,discontinued,company_id) values ( 57,'Altair 8800','1974-12-19',null,8);
insert into computer (id,name,introduced,discontinued,company_id) values ( 58,'IMSAI 8080','1975-08-01',null,9);
insert into computer (id,name,introduced,discontinued,company_id) values ( 59,'IMSAI Series Two',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 60,'VAX','1977-10-25',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values ( 61,'VAX 11/780','1977-10-25',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values ( 62,'VAX 11/750','1980-10-01',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values ( 63,'TX-2','1958-01-01',null,11);
insert into computer (id,name,introduced,discontinued,company_id) values ( 64,'TX-0','1956-01-01',null,11);
insert into computer (id,name,introduced,discontinued,company_id) values ( 65,'Whirlwind','1951-04-20',null,11);
insert into computer (id,name,introduced,discontinued,company_id) values ( 66,'ENIAC','1946-02-15','1955-10-02',12);
insert into computer (id,name,introduced,discontinued,company_id) values ( 67,'IBM PC','1981-08-12',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values ( 68,'Macintosh Classic',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 69,'Macintosh Classic II','1991-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 70,'Amiga','1985-01-01',null,14);
insert into computer (id,name,introduced,discontinued,company_id) values ( 71,'Amiga 1000',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( 72,'Amiga 500','1987-01-01',null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( 73,'Amiga 500+',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 74,'Amiga 2000','1986-01-01','1990-01-01',6);
insert into computer (id,name,introduced,discontinued,company_id) values ( 75,'Amiga 3000',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( 76,'Amiga 600','1992-03-01',null,6);
insert into computer (id,name,introduced,discontinued,company_id) values ( 77,'Macintosh 128K','1984-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 78,'Macintosh 512K','1984-09-10','1986-04-14',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 79,'Macintosh SE','1987-03-02','1989-08-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 80,'Macintosh SE/30','1989-01-19','1991-10-21',1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 81,'Canon Cat','1987-01-01',null,15);
insert into computer (id,name,introduced,discontinued,company_id) values ( 82,'Nokia 770',null,null,16);
insert into computer (id,name,introduced,discontinued,company_id) values ( 83,'Nokia N800','2007-01-01',null,16);
insert into computer (id,name,introduced,discontinued,company_id) values ( 84,'Mylo','2006-09-21',null,17);
insert into computer (id,name,introduced,discontinued,company_id) values ( 85,'OQO 02','2007-01-01',null,18);
insert into computer (id,name,introduced,discontinued,company_id) values ( 86,'OQO 01+',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 87,'Pinwheel calculator',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 88,'iBook',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 89,'MacBook','2006-05-16',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values ( 90,'NeXTstation','1990-01-01','1993-01-01',19);
insert into computer (id,name,introduced,discontinued,company_id) values ( 91,'NeXTcube','1988-01-01','1993-01-01',19);
insert into computer (id,name,introduced,discontinued,company_id) values ( 92,'NeXTstation Color Turbo',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 93,'NeXTstation Color',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 94,'NeXTstation Turbo',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 95,'NeXTcube Turbo',null,null,19);
insert into computer (id,name,introduced,discontinued,company_id) values ( 96,'NeXTcube 040',null,null,19);
insert into computer (id,name,introduced,discontinued,company_id) values ( 97,'NeXTcube 030',null,null,19);
insert into computer (id,name,introduced,discontinued,company_id) values ( 98,'Tinkertoy Tic-Tac-Toe Computer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values ( 99,'Z3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (100,'Z4',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (101,'Z1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (102,'Z2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (103,'Wang 2200','1973-05-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (104,'Wang VS',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (105,'Wang OIS',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (106,'BBC Micro',null,null,22);
insert into computer (id,name,introduced,discontinued,company_id) values (107,'IBM 650','1953-01-01','1962-01-01',13);
insert into computer (id,name,introduced,discontinued,company_id) values (108,'Cray-1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (109,'Cray-3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (110,'Cray-2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (111,'Cray-4',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (112,'Cray X1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (113,'Cray XD1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (114,'Cray T3D','1993-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (115,'Cray T3E','1995-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (116,'Cray C90',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (117,'Cray T90',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (118,'Cray SV1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (119,'Cray J90',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (120,'Cray XT3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (121,'Cray CS6400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (122,'Atari ST','1985-01-01','1993-01-01',20);
insert into computer (id,name,introduced,discontinued,company_id) values (123,'Amiga 2500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (124,'Amiga 2500',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (125,'Amiga 4000',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (126,'Amiga 3000UX',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (127,'Amiga 3000T',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (128,'Amiga 4000T',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (129,'Amiga 1200','1992-10-01','1996-01-01',6);
insert into computer (id,name,introduced,discontinued,company_id) values (130,'Atari 1040 STf','1986-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (131,'Atari 520 ST','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (132,'Atari 520 STfm','1986-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (133,'Atari 1040 STe','1989-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (134,'Atari MEGA STe','1991-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (135,'Atari 520 ST+','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (136,'Atari 520 STm','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (137,'Atari 130 ST','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (138,'Atari 260 ST','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (139,'Atari MEGA ST','1987-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (140,'Atari 520 STf','1986-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (141,'Atari 1040 STfm','1986-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (142,'Atari 2080 ST','1986-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (143,'Atari 260 ST+','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (144,'Atari 4160 STe','1988-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (145,'TRS-80 Color Computer 2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (146,'TRS-80 Color Computer 3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (147,'TRS-80 Model 1','1977-01-01',null,5);
insert into computer (id,name,introduced,discontinued,company_id) values (148,'Timex Sinclair 2068','1983-11-01','1984-04-01',23);
insert into computer (id,name,introduced,discontinued,company_id) values (149,'ZX Spectrum','1982-01-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (150,'Xerox Star','1981-01-01',null,26);
insert into computer (id,name,introduced,discontinued,company_id) values (151,'Xerox Alto',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (152,'Acorn Archimedes',null,null,22);
insert into computer (id,name,introduced,discontinued,company_id) values (153,'Nintendo Entertainment System',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (154,'Super Nintendo Entertainment System','1991-08-01','1999-01-01',24);
insert into computer (id,name,introduced,discontinued,company_id) values (155,'Super Famicom',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (156,'Nintendo GameCube',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (157,'Game Boy line',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (158,'PlayStation','1994-12-03',null,17);
insert into computer (id,name,introduced,discontinued,company_id) values (159,'PlayStation 2','2000-03-24',null,17);
insert into computer (id,name,introduced,discontinued,company_id) values (160,'Game & Watch',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (161,'EDSAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (162,'IBM System/4 Pi',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (163,'IBM AP-101',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (164,'IBM TC-1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (165,'IBM AP-101B',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (166,'IBM AP-101S',null,null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (167,'ProLiant',null,null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (168,'Http://nepomuk.semanticdesktop.org/xwiki/',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (169,'Sinclair QL','1984-01-01','1986-01-01',25);
insert into computer (id,name,introduced,discontinued,company_id) values (170,'Sinclair ZX81','1981-01-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (171,'Sinclair ZX80',null,null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (172,'Atari 65XE',null,null,20);
insert into computer (id,name,introduced,discontinued,company_id) values (173,'Deep Blue',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (174,'Macintosh Quadra 650',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (175,'Macintosh Quadra 610',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (176,'Macintosh Quadra 800',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (177,'Macintosh Quadra 950',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (178,'PowerBook 160',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (179,'PowerBook 145B',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (180,'PowerBook 170',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (181,'PowerBook 145',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (182,'PowerBook G3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (183,'PowerBook 140',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (184,'Macintosh IIcx',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (185,'Powerbook 180',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (186,'PowerBook G4',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (187,'Macintosh XL',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (188,'PowerBook 100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (189,'PowerBook 2400c',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (190,'PowerBook 1400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (191,'Macintosh Quadra 630',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (192,'Macintosh Quadra 660AV',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (193,'Macintosh Quadra 840AV',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (194,'PowerBook 5300',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (195,'PowerBook 3400c',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (196,'Macintosh Color Classic',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (197,'Macintosh 512Ke',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (198,'Macintosh IIsi',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (199,'Macintosh IIx',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (200,'PowerBook 500 series',null,null,null);


# --- !Downs

delete from computer;
delete from company;
