# --- Sample dataset

# --- !Ups

insert into computer (id,name,introduced,discontinued,company_id) values (201,'Power Macintosh G3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (202,'Macintosh IIci',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (203,'iMac G5','2004-08-31',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (204,'Power Mac G4',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (205,'Power Macintosh 7100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (206,'Power Macintosh 9600',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (207,'Power Macintosh 7200',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (208,'Power Macintosh 7300',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (209,'Power Macintosh 8600',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (210,'Power Macintosh 6200',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (211,'Power Macintosh 8100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (212,'Compact Macintosh',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (213,'Power Macintosh 4400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (214,'Power Macintosh 9500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (215,'Macintosh Portable',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (216,'EMac',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (217,'Power Macintosh 7600',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (218,'Power Mac G5',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (219,'Power Macintosh 7500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (220,'Power Macintosh 6100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (221,'Power Macintosh 8500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (222,'Macintosh IIvi',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (223,'Macintosh IIvx',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (224,'IMac G3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (225,'IMac G4',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (226,'Power Mac G4 Cube',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (227,'Intel iMac',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (228,'Deep Thought',null,null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (229,'Wii','2006-11-19',null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (230,'IBM System x',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (231,'IBM System i','2006-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (232,'IBM System z','2006-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (233,'IBM System p','2000-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (234,'LC 575',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (235,'Macintosh TV',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (236,'Macintosh Performa',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (237,'Macintosh II series',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (238,'Power Macintosh 6400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (239,'Power Macintosh 6500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (240,'Apple PenLite',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (241,'Wallstreet',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (242,'Twentieth Anniversary Macintosh',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (243,'Power Macintosh 5500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (244,'iBook G3',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (245,'Power Macintosh 5200 LC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (246,'Power Macintosh 5400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (247,'CM-1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (248,'MSX','1983-01-01','1995-01-01',28);
insert into computer (id,name,introduced,discontinued,company_id) values (249,'PlayStation 3',null,null,17);
insert into computer (id,name,introduced,discontinued,company_id) values (250,'MSX2','1986-01-01',null,29);
insert into computer (id,name,introduced,discontinued,company_id) values (251,'MSX2+','1988-01-01',null,30);
insert into computer (id,name,introduced,discontinued,company_id) values (252,'MSX turbo R','1990-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (253,'Panasonic FS A1GT',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (254,'Panasonic FS A1ST',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (255,'PDP-11',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (256,'PDP-1',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (257,'PDP-10',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (258,'PDP-8',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (259,'PDP-6',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (260,'DECSYSTEM-20',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (261,'PDP-7',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (262,'PDP-5',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (263,'PDP-12',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (264,'LINC',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (265,'PDP-14',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (266,'PDP-15',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (267,'PDP-16',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (268,'Cray X2','2007-01-01',null,31);
insert into computer (id,name,introduced,discontinued,company_id) values (269,'Cray X-MP','1982-01-01',null,31);
insert into computer (id,name,introduced,discontinued,company_id) values (270,'Evans & Sutherland ES-1',null,null,32);
insert into computer (id,name,introduced,discontinued,company_id) values (271,'Commodore VIC-20','1980-01-01',null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (272,'PowerBook 150',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (273,'MacBook Air','2008-01-15',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (274,'Digi-Comp I','1963-01-01',null,33);
insert into computer (id,name,introduced,discontinued,company_id) values (275,'Digi-Comp',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (276,'Digi-Comp II',null,null,33);
insert into computer (id,name,introduced,discontinued,company_id) values (277,'Manchester Mark I','1949-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (278,'Small-Scale Experimental Machine','1948-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (279,'Nintendo 64',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (280,'Game Boy Advance',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (281,'Game Boy',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (282,'Nintendo DS Lite',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (283,'Nintendo DS','2004-01-01',null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (284,'Game Boy Color',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (285,'Game Boy Advance SP',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (286,'Virtual Boy',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (287,'Game Boy Micro',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (288,'Roadrunner',null,null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (289,'HP 9000',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (290,'OMRON Luna-88K2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (291,'OMRON Luna-88K',null,null,34);
insert into computer (id,name,introduced,discontinued,company_id) values (292,'Motorola series 900',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (293,'Motorola M8120',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (294,'Triton Dolphin System 100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (295,'BBN TC2000','1989-08-01',null,35);
insert into computer (id,name,introduced,discontinued,company_id) values (296,'WRT54G',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (297,'ThinkPad','1992-01-01',null,36);
insert into computer (id,name,introduced,discontinued,company_id) values (298,'Apple Newton','1993-01-01','1998-01-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values (299,'Atanasoff-Berry Computer','1937-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (300,'Atlas Computer','1962-01-01','1974-01-01',null);
insert into computer (id,name,introduced,discontinued,company_id) values (301,'ASUS Eee PC 901',null,null,37);
insert into computer (id,name,introduced,discontinued,company_id) values (302,'ASUS Eee PC 701',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (303,'IBM 7030','1961-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (304,'System/38','1979-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (305,'System/36','1983-01-01','2000-01-01',13);
insert into computer (id,name,introduced,discontinued,company_id) values (306,'IBM 7090','1959-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (307,'IBM RT',null,null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (308,'System/360','1964-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (309,'IBM 801','1980-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (310,'IBM 1401','1959-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (311,'ASCI White','2001-01-01','2006-01-01',13);
insert into computer (id,name,introduced,discontinued,company_id) values (312,'Blue Gene',null,null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (313,'ASCI Blue Pacific','1998-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (314,'iPhone','2007-06-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (315,'Nokia N810','2007-10-17',null,16);
insert into computer (id,name,introduced,discontinued,company_id) values (316,'EDSAC 2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (317,'Titan',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (318,'Pilot ACE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (319,'HP Mini 1000','2008-10-29',null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (320,'HP 2133 Mini-Note PC','2008-04-15',null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (321,'Kogan Agora Pro','2008-12-04',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (322,'D-Series Machines',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (323,'ZX Spectrum 48K','1982-01-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (324,'ZX Spectrum 16K','1982-01-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (325,'ZX Spectrum 128','1985-09-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (326,'ZX Spectrum +3',null,null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (327,'ZX Spectrum +2','1986-01-01',null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (328,'ZX Spectrum +2A','1987-01-01',null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (329,'ZX Spectrum +','1984-06-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (330,'Acer Extensa',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (331,'Acer Extensa 5220',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (332,'Dell Latitude',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (333,'Toshiba Satellite',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (334,'Timex Sinclair 2048',null,null,23);
insert into computer (id,name,introduced,discontinued,company_id) values (335,'Sprinter',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (336,'Timex Computer 2048',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (337,'Pentagon',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (338,'Belle',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (339,'Loki',null,null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (340,'Hobbit',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (341,'NeXT Computer',null,null,19);
insert into computer (id,name,introduced,discontinued,company_id) values (342,'TRS-80',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (343,'TRS-80 Model 2','1980-01-01',null,5);
insert into computer (id,name,introduced,discontinued,company_id) values (344,'TRS-80 Model 3',null,null,5);
insert into computer (id,name,introduced,discontinued,company_id) values (345,'STacy','1989-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (346,'ST BOOK','1990-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (347,'Atari 520 STE','1989-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (348,'Amiga 2000 Model A',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (349,'Amiga 2000 Model B',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (350,'Amiga 2000 Model C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (351,'IBM 3270',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (352,'CALDIC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (353,'Modbook',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (354,'Compaq SystemPro',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (355,'ARRA',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (356,'IBM System Cluster 1350',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (357,'Finite element machine',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (358,'ES7000',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (359,'HP MediaSmart Server',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (360,'HP Superdome',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (361,'IBM Power Systems','2008-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (362,'Oslo Analyzer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (363,'Microsoft Softcard',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (364,'WITCH',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (365,'Analytical engine',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (366,'EDVAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (367,'BINAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (368,'Earth Simulator',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (369,'BARK',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (370,'Harvard Mark I','1944-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (371,'ILLIAC IV',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (372,'ILLIAC II',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (373,'ILLIAC III',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (374,'Water integrator',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (375,'CSIRAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (376,'System X',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (377,'Harvest',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (378,'ChipTest',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (379,'HiTech',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (380,'Bomba',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (381,'ACE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (382,'ASCI Red',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (383,'ASCI Thors Hammer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (384,'ASCI Purple','2005-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (385,'ASCI Blue Mountain',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (386,'Columbia',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (387,'HP Integrity',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (388,'APEXC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (389,'Datasaab D2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (390,'BRLESC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (391,'DYSEAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (392,'SSEC','1948-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (393,'Hydra',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (394,'FUJIC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (395,'RAYDAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (396,'Harvard Mark III',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (397,'DATAR',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (398,'ReserVec',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (399,'DASK',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (400,'UTEC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (401,'DRTE Computer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (402,'PowerEdge',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (403,'Apple Network Server',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (404,'Goodyear MPP',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (405,'Macintosh 128K technical details',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (406,'Power Macintosh G3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (407,'CER-10',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (408,'CER-20',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (409,'IBM BladeCenter','2002-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (410,'Wisconsin Integrally Synchronized Computer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (411,'Amstrad CPC',null,null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (412,'Amstrad CPC 6128',null,null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (413,'Amstrad CPC 664',null,null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (414,'Amstrad CPC 464',null,null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (415,'Intergraph',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (416,'Enterprise',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (417,'MTX500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (418,'Acorn Electron',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (419,'Sony Vaio P','2009-02-01',null,17);
insert into computer (id,name,introduced,discontinued,company_id) values (420,'VAIO',null,null,17);
insert into computer (id,name,introduced,discontinued,company_id) values (421,'Sony Vaio P VGN-P588E/Q',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (422,'Sony Vaio P VGN-P530H/G',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (423,'Sony Vaio P VGN-P530H/W',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (424,'Sony Vaio P VGN-P530H/Q',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (425,'Sony Vaio P VGN-P530H/R',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (426,'Sony Vaio P VGN-P588E/R',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (427,'Sony Vaio P VGN-P598E/Q',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (428,'Timex Sinclair 1000','1982-07-01',null,23);
insert into computer (id,name,introduced,discontinued,company_id) values (429,'Komputer 2086',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (430,'Galaksija',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (431,'Vector-06C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (432,'Elektronika BK',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (433,'Sun386i',null,null,39);
insert into computer (id,name,introduced,discontinued,company_id) values (434,'Xerox Daybreak','1985-01-01','1989-01-01',null);
insert into computer (id,name,introduced,discontinued,company_id) values (435,'Xerox NoteTaker',null,null,26);
insert into computer (id,name,introduced,discontinued,company_id) values (436,'D4a','1965-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (437,'LGP-30',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (438,'LGP-21',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (439,'ASUS Eee PC 900','2008-05-01',null,37);
insert into computer (id,name,introduced,discontinued,company_id) values (440,'Atari TT030',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (441,'Bi Am ZX-Spectrum 48/64',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (442,'Bi Am ZX-Spectrum 128',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (443,'PlayStation Portable',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (444,'MSI Wind Netbook',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (445,'Sharp Mebius NJ70A','2009-04-21',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (446,'HTC Snap',null,null,41);
insert into computer (id,name,introduced,discontinued,company_id) values (447,'Commodore Educator 64',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (448,'Amiga 1500',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (449,'Commodore 65',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (450,'Commodore 16',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (451,'Commodore CBM-II',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (452,'Commodore Plus/4',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (453,'Commodore LCD',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (454,'Commodore MAX Machine',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (455,'Aster CT-80',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (456,'Test','2009-01-01','2009-01-01',null);
insert into computer (id,name,introduced,discontinued,company_id) values (457,'MSI GX723',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (458,'Eee PC 1000HV','2009-05-22',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (459,'VTech Laser 200','1983-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (460,'CrunchPad',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (461,'Neo Geo','1990-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (462,'Sega Mega Drive',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (463,'Sega Master System',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (464,'TurboGrafx-16',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (465,'Sun-3',null,null,39);
insert into computer (id,name,introduced,discontinued,company_id) values (466,'Pleiades',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (467,'IBM Sequoia',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (468,'Inves Spectrum 48k plus',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (469,'iPhone 3G',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (470,'iPhone 3GS',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (471,'Beagle Board',null,null,40);
insert into computer (id,name,introduced,discontinued,company_id) values (472,'HP nPar',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (473,'MacBook Family',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (474,'Reservisor',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (475,'BladeSystem',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (476,'lenovo thinkpad t60p',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (477,'lenovo thinkpad x200',null,null,36);
insert into computer (id,name,introduced,discontinued,company_id) values (478,'lenovo thinkpad t60',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (479,'lenovo thinkpad w700',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (480,'lenovo thinkpad t41',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (481,'lenovo thinkpad z61p',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (482,'lenovo thinkpad x61s',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (483,'lenovo thinkpad t43',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (484,'lenovo thinkpad r400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (485,'lenovo thinkpad x60s',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (486,'lenovo thinkpad x301',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (487,'lenovo thinkpad t42',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (488,'lenovo thinkpad r61',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (489,'lenovo thinkpad w500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (490,'lenovo thinkpad sl400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (491,'lenovo thinkpad x40',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (492,'lenovo thinkpad x200 tablet',null,null,36);
insert into computer (id,name,introduced,discontinued,company_id) values (493,'lenovo thinkpad t400s',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (494,'Nokia N900','2009-10-01',null,16);
insert into computer (id,name,introduced,discontinued,company_id) values (495,'Internet Tablet',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (496,'Meiko Computing Surface','1986-01-01','1993-01-01',null);
insert into computer (id,name,introduced,discontinued,company_id) values (497,'CS-2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (498,'IBM 701','1952-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (499,'IBM 5100','1975-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (500,'AN/FSQ-7','1958-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (501,'AN/FSQ-32','1960-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (502,'IBM CPC','1949-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (503,'System/34','1978-01-01','1983-01-01',13);
insert into computer (id,name,introduced,discontinued,company_id) values (504,'System/32','1975-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (505,'System/3','1969-01-01','1985-01-01',13);
insert into computer (id,name,introduced,discontinued,company_id) values (506,'IBM 305','1956-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (507,'English Electric DEUCE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (508,'CER-203',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (509,'CER-22',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (510,'Kentucky Linux Athlon Testbed',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (511,'QNAP TS-101',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (512,'iPad','2010-01-01','2011-03-02',1);
insert into computer (id,name,introduced,discontinued,company_id) values (513,'iPhone 2G',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (514,'Inslaw',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (515,'WePad','2010-07-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (516,'MacBook Parts',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (517,'MacBook 13-inch Core 2 Duo 2.13GHz (MC240LL/A) DDR2 Model',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (518,'MacBook 13-inch Core 2 Duo 2.13GHz (MC240T/A) DDR2 Model',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (519,'MacBook 13-inch Core 2 Duo 2.13GHz (MC240X/A) DDR2 Model',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (520,'MacBook 13-inch Core 2 Duo 2.26GHz (Unibody MC207LL/A) DDR3 Model',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (521,'MC240LL/A',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (522,'D.K.COMMUNICATION',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (523,'iPhone 4',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (524,'Nintendo 3DS','2010-03-23',null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (525,'ASUS Eee PC 1005PE','2010-01-01',null,37);
insert into computer (id,name,introduced,discontinued,company_id) values (526,'National Law Enforcement System',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (527,'BlackBerry PlayBook',null,null,42);
insert into computer (id,name,introduced,discontinued,company_id) values (528,'Barnes & Noble nook','2009-10-20',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (529,'SAM Coupé',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (530,'HTC Dream','2008-10-22',null,41);
insert into computer (id,name,introduced,discontinued,company_id) values (531,'Samsung Galaxy Tab','2010-09-02',null,43);
insert into computer (id,name,introduced,discontinued,company_id) values (532,'BlackBerry PlayBook','2010-09-27',null,42);
insert into computer (id,name,introduced,discontinued,company_id) values (533,'Tianhe-I',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (534,'Kno',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (535,'ThinkPad 701 C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (536,'ThinkPad 340 CSE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (537,'ThinkPad 755 CX',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (538,'ThinkPad 755 CE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (539,'ThinkPad 370 C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (540,'Coleco Adam','1983-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (541,'Nebulae',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (542,'Alex eReader',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (543,'Acer Iconia',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (544,'Archos 101',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (545,'Fujitsu Lifebook T900',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (546,'Motorola Xoom',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (547,'ViewSonic G Tablet',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (548,'DEC Professional','1982-01-01',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (549,'DEC Multia','1994-11-07',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (550,'DEC Firefly',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (551,'DEC 3000 AXP',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (552,'DEC 2000 AXP','1993-05-25',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (553,'DEC 4000 AXP','1992-11-10',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (554,'DEC 7000/10000 AXP','1992-11-10',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (555,'DEC Professional 350',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (556,'DEC Rainbow 100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (557,'DEC Professional 325',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (558,'DECmate II',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (559,'DECmate',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (560,'DECsystem',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (561,'NetApp Filer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (562,'DEC GT40',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (563,'ecoATM',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (564,'MindWave BrainCubed Education Bundle',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (565,'PalmPilot',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (566,'Upcoming iPhone 5',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (567,'Dell Inspiron 560 Desktop Computer ',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (568,'IPad 2',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (569,'HP TouchPad','2011-02-09',null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (570,'HP Veer','2011-02-09',null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (571,'Lenovo Thinkpad Edge 11',null,null,36);
insert into computer (id,name,introduced,discontinued,company_id) values (572,'Dell Vostro',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (573,'Gateway LT3103U','2008-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (574,'iPhone 4S','2011-10-14',null,1);

# --- !Downs

delete from computer where id > 250;
